repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.62.3'
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      name: TFLint init
      args:
        - --args=--init
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_tflint
      name: TFLint validation
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_tfsec
      args:
        - --args=--config-file=__GIT_WORKING_DIR__/tfsec.yml
- repo: local
  hooks:
    - id: terraform_docs
      name: Terraform docs
      description: Inserts input and output documentation into README.md (using terraform-docs).
      entry: ./hacks/terraform-docs.sh
      language: script
      pass_filenames: false
